### ISSUE TITLE
[Q] Cancelling pending download

### ISSUE THREAD

**Issue by grabbou** [johanneslumpe/react-native-fs#58]
Hey,

In my implementation, I have a queue of items to be downloaded. I am about to implement `stopDownload` however, I've noticed weird behaviour on iOS I wanted to double check with you.

When I call fs.unlink on a path that I previously used with fs.downloadFile and that operation has not finished yet - it will resolve successfully after the file is downloaded, however, fs.readdir call will not have that file.

Is that expected? Feels a bit weird, especially given that in readme it says "partial files will remain on file system"

**Comment by johanneslumpe** [comment]
@grabbou I haven't tried this before so I can only assume what might be happening: If you unlink a file while it is being downloaded, it's possible that ios will either finish the download without continuing to save to disk or that the file might be marked as to be removed internally and will be removed as soon as all access has seized. This is a long shot but right now that's the only thing that would make sense to me given the behavior that you're describing.

The download feature was not added by myself and I haven't used it. The note in the readme only refers to the use of `stopDownload`, which does nothing else but to cancel the connection. But since you are also invoking `fs.unlink` I'd assume that there might be a weird interference going on, as per my assumption above.

**Comment by johanneslumpe** [comment]
@grabbou Is this still an issue?

**Comment by grabbou** [comment]
Not at all, we can close it! Thanks for answering ;)

**Comment by johanneslumpe** [comment]
:+1:
